SELECT * FROM MEMBER;

select * from board;

drop table board;

SELECT * FROM orderdetail;

INSERT INTO BOARD (BNUM,MID,PNUM,BCONTENT,BSTAR,MNAME) VALUES (1,'DAEHWAN',1,'테스트 글 입니다.',5,'대환');


INSERT INTO SUBSCRIPTION (SUBNUM,SUBNAME,SUBPRICE) VALUES (1,'종합 주주박스',39000);
INSERT INTO SUBSCRIPTION (SUBNUM,SUBNAME,SUBPRICE) VALUES (2,'증류주 주주박스',49000);
INSERT INTO SUBSCRIPTION (SUBNUM,SUBNAME,SUBPRICE) VALUES (3,'과일주 주주박스',52000);

